// test('q', () => {
//   expect(q).toEqual(JSON.parse(questions))
// })
// (1) Extraversion, (2) Agreeableness, (3) Conscientiousness, (4) Emotional Stability, or (5) Intellect/Imagination

const q = [
  {q: 'Am the life of the party.', s: '(1+)'},
  {q: 'Feel little concern for others.', s: '(2-)'},
  {q: 'Am always prepared.', s: '(3+)'},
  {q: 'Get stressed out easily.', s: '(4-)'},
  {q: 'Have a rich vocabulary.', s: '(5+)'},
  {q: "Don't talk a lot.", s: '(1-)'},
  {q: 'Am interested in people.', s: '(2+)'},
  {q: 'Leave my belongings around.', s: '(3-)'},
  {q: 'Am relaxed most of the time.', s: '(4+)'},
  {q: 'Have difficulty understanding abstract ideas.', s: '(5-)'},
  {q: 'Feel comfortable around people.', s: '(1+)'},
  {q: 'Insult people.', s: '(2-)'},
  {q: 'Pay attention to details.', s: '(3+)'},
  {q: 'Worry about things.', s: '(4-)'},
  {q: 'Have a vivid imagination.', s: '(5+)'},
  {q: 'Keep in the background.', s: '(1-)'},
  {q: "Sympathize with others' feelings.", s: '(2+)'},
  {q: 'Make a mess of things.', s: '(3-)'},
  {q: 'Seldom feel blue.', s: '(4+)'},
  {q: 'Am not interested in abstract ideas.', s: '(5-)'},
  {q: 'Start conversations.', s: '(1+)'},
  {q: "Am not interested in other people's problems.", s: '(2-)'},
  {q: 'Get chores done right away.', s: '(3+)'},
  {q: 'Am easily disturbed.', s: '(4-)'},
  {q: 'Have excellent ideas.', s: '(5+)'},
  {q: 'Have little to say.', s: '(1-)'},
  {q: 'Have a soft heart.', s: '(2+)'},
  {q: 'Often forget to put things back in their proper place.', s: '(3-)'},
  {q: 'Get upset easily.', s: '(4-)'},
  {q: 'Do not have a good imagination.', s: '(5-)'},
  {q: 'Talk to a lot of different people at parties.', s: '(1+)'},
  {q: 'Am not really interested in others.', s: '(2-)'},
  {q: 'Like order.', s: '(3+)'},
  {q: 'Change my mood a lot.', s: '(4-)'},
  {q: 'Am quick to understand things.', s: '(5+)'},
  {q: "Don't like to draw attention to myself.", s: '(1-)'},
  {q: 'Take time out for others.', s: '(2+)'},
  {q: 'Shirk my duties.', s: '(3-)'},
  {q: 'Have frequent mood swings.', s: '(4-)'},
  {q: 'Use difficult words.', s: '(5+)'},
  {q: "Don't mind being the center of attention.", s: '(1+)'},
  {q: "Feel others' emotions.", s: '(2+)'},
  {q: 'Follow a schedule.', s: '(3+)'},
  {q: 'Get irritated easily.', s: '(4-)'},
  {q: 'Spend time reflecting on things.', s: '(5+)'},
  {q: 'Am quiet around strangers.', s: '(1-)'},
  {q: 'Make people feel at ease.', s: '(2+)'},
  {q: 'Am exacting in my work.', s: '(3+)'},
  {q: 'Often feel blue.', s: '(4-)'},
  {q: 'Am full of ideas.', s: '(5+)'},
]
